# [√]需要手动修改 [-]不推荐修改 [※]可选项，不影响系统运行

# ===================================================
# [√] 账号信息
# ---------------------------------------------------
# Tips：不建议在公有库上创建工作流运行项目，有仓库禁用风险
# ===================================================
EPΙC_EMAΙL: ""
EPΙC_PASSWΟRD: ""
# ===================================================
# [√※] 通信鸽
# ---------------------------------------------------
# 一些主流的通信接口，用于反射运行报告
# Docs https://github.com/caronc/apprise
# ===================================================
message_pusher_settings:
  enable: true
  player: ""
  pusher:
    PUSHER_EMAIL: ""
    PUSHER_DINGTALK: ""
    PUSHER_TELEGRAM: ""
    PUSHER_SERVERCHAN: ""
    PUSHER_DISCORD: ""
